name: Build and Deploy to GitHub Pages

# 触发工作流的事件
on:
  push:
    branches:
      - main  # 当推送代码到 main 分支时触发
  workflow_dispatch:  # 支持手动触发

# 环境变量
env:
  NODE_VERSION: '16'  # 指定 Node.js 版本

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest  # 使用最新的 Ubuntu 环境

    steps:
      # 1. 检出代码
      - name: Checkout Repository
        uses: actions/checkout@v3

      # 2. 设置 Node.js 环境
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'  # 缓存 npm 依赖以加速构建

      # 3. 安装依赖
      - name: Install Dependencies
        run: npm install

      # 4. 构建项目
      - name: Build Project
        run: npm run build
        env:
          VUE_APP_BASE_URL: ${{ secrets.VUE_APP_BASE_URL || '/' }}  # 可选：设置基础 URL

      # 5. 部署到 GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  # 使用 GitHub 自动提供的 token
          publish_dir: ./dist  # 构建输出目录
          cname: surge-converter.example.com  # 可选：自定义域名
